<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.12">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MvInfrastructure\MvInfrastructure.csproj"/>
        <ProjectReference Include="..\MvApplication\MvApplication.csproj"/>
    </ItemGroup>

</Project>
